# Generated by Django 5.0.1 on 2024-02-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
