# Generated by Django 5.0.1 on 2024-02-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_comment_comment_body_comment_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='product_name',
        ),
    ]
