# Generated by Django 5.0.1 on 2024-02-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_name_comment_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='url',
            new_name='product_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='product_url',
        ),
    ]
